name: Build and push Docker image
on: workflow_dispatch
jobs:
  build-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Generate version
        run: |
          echo "VERSION=$(date +'%Y.%m.%d')-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      name: Login to Amazon ECR
      uses: aws-actions/amazon-ecr-login@v2
        
      - name: Get npm cache directory
        id: npm-cache-dir
        shell: bash
        run: echo "dir=$(npm config get cache)" >> ${GITHUB_OUTPUT}

      - name: Setup Cargo cache
        uses: actions/cache@v3
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            backend/target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

      - name: Setup npm cache
        uses: actions/cache@v3
        with:
          path: ${{ steps.npm-cache-dir.outputs.dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-node-

      - name: Setup Cargo
        run: |
          sudo apt install cargo

      - name: Install sqlx via Cargo
        run: |
          cargo install sqlx-cli

      - name: Prepare sqlx queries
        run: |
          cd backend
          cargo sqlx prepare

      - name: Build
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          docker buildx build --platform linux/amd64 -t windmill:${VERSION} .

      - name: Push image to Amazon ECR
        env:
          VERSION: ${{ env.VERSION }}
          REPO: 859499744640.dkr.ecr.sa-east-1.amazonaws.com
        run: |
          docker push ${REPO}/windmill:${VERSION}

      - name: Create version tag on repository
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          git tag build/$VERSION
          git push --tags
