name: Build and push Docker image
jobs:
  build-push-docker-image:
    name: Build and push Docker image
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: "mobiltracker-windmill"
        
      - name: Generate version
        run: |
          echo "VERSION=$(date +'%Y.%m.%d')-$GITHUB_RUN_NUMBER" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: sa-east-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v1
        
      - name: Build
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          docker buildx build --platform linux/amd64 -t windmill:${VERSION} .
          
      - name: Push image to Amazon ECR
        env:
          VERSION: ${{ env.VERSION }}
          REPO: 859499744640.dkr.ecr.sa-east-1.amazonaws.com
        run: |
          docker push windmill:${VERSION}
      
      - name: Create version tag on repository
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          git tag build/$VERSION
          git push --tags
